config build&push docker image

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -19,20 +19,20 @@ jobs:
 
     runs-on: ubuntu-latest
 
-    services:
-      mysql:
-        image: mysql:latest
-        env:
-          MYSQL_ROOT_PASSWORD: rootpassword
-          MYSQL_DATABASE: dream_shops_db
-        ports:
-          - 3306:3306
-        options: >-
-          --health-cmd="mysqladmin ping --silent"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
-    
+#    services:
+#      mysql:
+#        image: mysql:latest
+#        env:
+#          MYSQL_ROOT_PASSWORD: rootpassword
+#          MYSQL_DATABASE: dream_shops_db
+#        ports:
+#          - 3306:3306
+#        options: >-
+#          --health-cmd="mysqladmin ping --silent"
+#          --health-interval=10s
+#          --health-timeout=5s
+#          --health-retries=5
+
 
     steps:
     - uses: actions/checkout@v4
@@ -44,12 +44,12 @@ jobs:
         cache: maven
 
     # Wait for MySQL to be ready
-    - name: Wait for MySQL to be ready
-      run: |
-             while ! mysqladmin -h127.0.0.1 -uroot -proot ping --silent; do
-               echo "Waiting for MySQL to be ready..."
-               sleep 2
-             done
+#    - name: Wait for MySQL to be ready
+#      run: |
+#             while ! mysqladmin -h127.0.0.1 -uroot -proot ping --silent; do
+#               echo "Waiting for MySQL to be ready..."
+#               sleep 2
+#             done
 
     - name: Build with Maven
       run: mvn clean install
